### ISSUE TITLE
err: Could not prefetch package provider 'cpanm'

### ISSUE THREAD

**Issue by jskarpe** [torrancew/puppet-cpanm#1]
It seems to be registered and working:

info: Retrieving plugin
notice: /File[/var/lib/puppet/lib/puppet/provider/package]/ensure: created
notice: /File[/var/lib/puppet/lib/puppet/provider/package/cpanm.rb]/ensure: defined content as '{md5}1fa58b7a1c951cf1f666061f354b84ae'
info: Loading downloaded plugin /var/lib/puppet/lib/puppet/provider/package/cpanm.rb

But I'm given this error:

err: Could not prefetch package provider 'cpanm'

What am I doing wrong?

Puppet 2.7.11

**Comment by jskarpe** [comment]
debug: Puppet::Type::Package::ProviderCpanm: Executing '/usr/bin/perldoc -t perllocal'

Turns out perl-doc package was missing from clean Ubuntu 12.04 install. Maybe an idea to add this in the install script?

**Comment by torrancew** [comment]
Sure thing - this module definitely needs some love, but I'm happy to see others starting to use it. Will push a fix as soon as I can, though the holiday season has me a bit busy.

**Comment by torrancew** [comment]
@Yuav,

Can you confirm that this fails more gracefully for you now?

**Comment by torrancew** [comment]
Closing this one, due to lack of response. Feel free to re-open if this pops up again.
